### ISSUE TITLE
List installation dependencies

### ISSUE THREAD

**Issue by ttimbers** [ryanhomer/jupyterext-text-shortcuts#1]
I just tried: `jupyter labextension install @techrah/text-shortcuts` and got the following error:

```
An error occured.
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /var/folders/67/sdt7v3y13m73fmpzd48c4wd40000gp/T/jupyterlab-debug-vyjvdca4.log
```

My system os OSX 0.14.6, and I don't have those dependencies installed. I do however have Jupyter Lab installed. 

Suggest that you list dependencies, or if [these](https://github.com/ryanhomer/jupyterext-text-shortcuts#development) are really the dependencies, I would move this further up the page (before? the installation instructions) to make this more obvious.

**Comment by ryanhomer** [comment]
Added the dependencies to the README. These are required in general to install Jupyter Lab extensions according to the [docs](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html), but worth listing them. Thanks.
