### ISSUE TITLE
error while installing jupyterlab extensions

### ISSUE THREAD

**Issue by kunalvshah** [ryanhomer/jupyterext-text-shortcuts#10]
Hi, I am receiving error while installing this extension, both using command line and through jupyterlab extension tab.

It says "The extension "@techrah/text-shortcuts" does not yet support the current version of JupyterLab"

Is there any version dependency to Jupyterlab?

Please see the screenshot attached.

Thanks
![Screenshot from 2021-01-19 18-09-48](https://user-images.githubusercontent.com/13920662/105035786-927eda00-5a81-11eb-930b-8b41606ee76f.png)

**Comment by Pweidemueller** [comment]
I experience the same problem. I'm using jupyterlab version 3.0.5.

**Comment by ryanhomer** [comment]
I’ll need to test compatibility with JL 3.x and make appropriate adjustments. I’ll update this thread when I have more information.

**Comment by ryanhomer** [comment]
Thanks for reporting this. Now resolved with v0.1.16 (#11)
