### ISSUE TITLE
Failed to save shortcuts user preferences 

### ISSUE THREAD

**Issue by Felihong** [ryanhomer/jupyterext-text-shortcuts#2]
Hi there, 

first of all, thanks for providing such a useful toolkit. 

I now have a small question regarding saving the shortcuts user preferences. After installing and enabling the extension, I add some test shortcuts and want to save it as described in the document. However the icon stays unresponsive (grey color) and I can't save the modifications. 

![Screenshot 2020-01-29 at 10 21 22](https://user-images.githubusercontent.com/28823328/73343782-776bf680-4281-11ea-8973-135319ac3c02.png)

**Environments**
- jupyter lab `v1.2.6`
- techrah/text-shortcuts `v0.0.6` 
- nodejs `v12.4.0` (installed via conda)

Thanks for your help!

**Comment by Felihong** [comment]
Hi again, I guess I just found the answer. I originally copied the sample customization from the document, it seems like I have to add a `comma` symbol at the end of shortcuts to make this json format work. 

```
{
    "shortcuts": [
        {
            "command": "text-shortcuts:insert-text",
            "args": {
                "text": "%>%",
                "autoPad": true
            },
            "keys": [
                "Accel Shift M"
            ],
            "selector": "body"
        },
        {
            "command": "text-shortcuts:insert-text",
            "args": {
                "text": "<-",
                "autoPad": true
            },
            "keys": [
                "Alt -"
            ],
            "selector": "body"
        },
    ]
}
```

**Comment by ryanhomer** [comment]
That's weird. I do not have to add the extra `,` in order to save. In fact, that extra comma technically makes it invalid JSON.

Anyway, glad you got it to work! 👍
